### ISSUE TITLE
React SDK doesn't load in React 18's StrictMode 

### ISSUE THREAD

**Issue by TatarczykAVitesse** [splitio/react-client#221]
Hello

I've been trying to integrate Split in my app but the features would never load (`isReady` property is never set to `true`) and it turned out it's because in the development mode I'm using React's StrictMode. As soon as I moved the `SplitFactoryProvider` outside of it, everything starts to work properly.

I prepared a reproduction repo based on the React's example app https://github.com/TatarczykAVitesse/react-typescript-sdk-examples

Interestingly, as soon as I downgrade from version 2 to version 1 of `@splitsoftware/splitio-react`, it starts to work with no further changes

**Comment by EmilianoSanchez** [comment]
Hi @TatarczykAVitesse, 

We will include a fix for this in the next release as soon as possible. The fix has already been developed here: https://github.com/splitio/react-client/pull/217

In the meantime, you can try a release candidate that includes a fix: `"@splitsoftware/splitio-react": "^2.0.1-rc.0"`

I will keep the issue open, let you know, and then close it when the release is done :)

Thanks for sharing!

**Comment by EmilianoSanchez** [comment]
Hi @TatarczykAVitesse ,

I’m closing this issue for now, as we’ve just released React SDK v2.0.1, which includes the update to support React Strict Mode, among other improvements and bugfixes. Try this new version on your side.

Thanks again!

**Comment by MaxArnautFrontegg** [comment]
It's still reproducing for me on 2.0.1. isReady is never set to true...
For now stopped on 1.13.0 it works as expected.

**Comment by EmilianoSanchez** [comment]
I am sorry to hear that @MaxArnautFrontegg.

I tried reproducing it on my side but wasn't able to. After updating `@splitsoftware/splitio-react` to 2.0.1  in https://github.com/TatarczykAVitesse/react-typescript-sdk-examples and running the app with `StrictMode`, `isReady` is set to true as expected.

So, I assume you are facing the issue in a different project. Could you please extend your [example app](https://github.com/TatarczykAVitesse/react-typescript-sdk-examples) to reproduce the issue with 2.0.1?

Looking forward to your example so we can investigate further!
